# Metrics Cops

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "cache/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "spec/support/fixture_builder.rb"
    - "tmp/**/*"
    - "db/data/*"
    - "db/data_schema.rb"
    - "db/migrate/*"
    - "db/schema.rb"
    - "config/initializers/*"

  TargetRubyVersion: 3.1.1

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true

Layout/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
  Enabled: true

Layout/IndentationWidth:
  Description: 'Use 2 spaces for indentation.'
  Width: 2
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 5 lines of code.'
  StyleGuide: '<https://github.com/bbatsov/ruby-style-guide#short-methods>'
  Max: 8
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false